### ISSUE TITLE
Execute a command to initialise some stuff

### ISSUE THREAD

**Issue by siketyan** [siketyan/ghr#29]
```shell
ghr clone siketyan/test --init npm
```

will run `npm i` in the repository directory after cloning.
It requires configuration before using the feature.

```toml
[initializers.npm]
cd = { cmd = "npm", args = ["i"] }
default = { cmd = "npm", args = ["ci"] }
```

With the configuration above, ghr will execute `npm i` after `ghr cd`, otherwise `npm ci`.
